/**
 * The English dictionary is the source of truth — its `typeof` is used
 * as the type for all other locales so missing translations are caught
 * by TypeScript.
 */
export const en = {
  meta: {
    title: "OfferShield — Understand contracts before you sign",
    description:
      "OfferShield turns dense legal text into plain-English summaries, risk flags, obligations, and smart questions to ask. Built with love using MiniMax-M3.",
  },
  nav: {
    howItWorks: "How it works",
    features: "Features",
    disclaimer: "Disclaimer",
    status: "Status",
  },
  hero: {
    badge: "AI-powered contract explainer",
    h1Before: "Understand contracts",
    h1Highlight: "before you sign.",
    subhead:
      "OfferShield turns dense legal text into plain-English summaries, risk flags, obligations, and smart questions to ask — ",
    subheadHighlight: "built with love using MiniMax-M3",
    ctaPrimary: "Try a sample",
    ctaSecondary: "Paste your document",
    private:
      "Private by default — text analyzed only to generate your report",
    educational: "Educational, not legal advice",
  },
  howItWorks: {
    tag: "How it works",
    title: "Three steps. About a minute.",
    steps: [
      {
        title: "Paste or upload",
        body:
          "Drop in a contract, offer letter, NDA, or any document — text or PDF. Or try a built-in sample.",
      },
      {
        title: "Click analyze",
        body:
          "OfferShield reads the document, identifies key clauses, and surfaces risks in a few seconds.",
      },
      {
        title: "Read your report",
        body:
          "Get a plain-English explanation, red flags, obligations, and questions to ask before signing.",
      },
    ],
  },
  features: {
    tag: "What you get",
    title: "Built to help you make better decisions.",
    items: [
      {
        title: "Plain-English explanations",
        body:
          "Get a calm walkthrough of what the document actually does — no legal jargon required.",
      },
      {
        title: "Risk flags you can act on",
        body:
          "Color-coded severity for every concern, with the specific clause it came from.",
      },
      {
        title: "Key dates & obligations",
        body:
          "Deadlines, renewal triggers, and what each party owes — extracted and laid out clearly.",
      },
      {
        title: "Smart questions to ask",
        body:
          "A copyable list of specific, useful questions for the other side or your lawyer.",
      },
      {
        title: "Multiple document types",
        body:
          "Offer letters, freelance contracts, NDAs, SaaS terms, vendor agreements, and more.",
      },
      {
        title: "Private by default",
        body:
          "Your document text is used only to generate your report. Nothing is stored.",
      },
    ],
  },
  trust: {
    items: [
      {
        title: "Private by default",
        body:
          "Document text is sent to the model only to generate your report. Nothing is stored.",
      },
      {
        title: "Server-side AI",
        body:
          "All analysis runs on the server. Your API key, if configured, never reaches the browser.",
      },
      {
        title: "No login required",
        body:
          "Open the app and use it. No account, no email, no friction.",
      },
    ],
  },
  disclaimer: {
    title:
      "OfferShield provides educational information, not legal advice.",
    body:
      "The analysis you receive is generated by an AI and is intended to help you understand a document, not to replace a qualified lawyer. Specific facts — your jurisdiction, the other party's practices, and the full contract context — can change what each term means in practice. For any decision with real consequences, please consult a licensed attorney in your jurisdiction.",
  },
  footer: {
    copyright: (year: number) => `© ${year} OfferShield`,
    by: "by",
    creditAria: "Blaze on X (opens in a new tab)",
    builtWith: "Built with",
    using: "using",
    model: "MiniMax-M3",
  },
  analyzer: {
    trust: "Private by default · not stored · analyzed only to generate your report",
    byok: {
      collapsedLabel:
        "Use your own MiniMax-M3 or Anthropic key (optional)",
      activeLabel: (masked: string) => `Using your key · ${masked}`,
      description:
        "Paste your key and we'll use it for your analyses. Your key is saved only in your browser (localStorage) and sent only to the model for your requests — never logged or stored on our servers.",
      placeholder: "sk-cp-… or sk-ant-…",
      showKey: "Show key",
      hideKey: "Hide key",
      save: "Save",
      clear: "Clear",
      clearAria: "Clear saved key",
      invalidError: "That doesn't look like a valid MiniMax or Anthropic key.",
      formatNote:
        "Format check only — the request itself runs against the model. If your key is invalid you'll get a 4xx from the provider, surfaced as a clear error.",
    },
    tabs: {
      paste: "Paste text",
      upload: "Upload PDF",
      sample: "Try a sample",
    },
    paste: {
      placeholder:
        "Paste your contract, offer letter, NDA, or any document here…",
      charCounter: (count: number, max: number) =>
        `${count.toLocaleString()} / ${max.toLocaleString()} characters`,
      charCounterWithMeta: (count: number, max: number, words: number, mins: number) =>
        `${count.toLocaleString()} / ${max.toLocaleString()} characters · ${words.toLocaleString()} words · ~${mins} min read`,
      tooShort: (min: number) => `Add a bit more — at least ${min} characters.`,
      tooLong: (max: number) => `Too long. Trim to ${max.toLocaleString()} characters.`,
    },
    upload: {
      dropZone: "Drop a PDF here, or click to choose",
      replace: "Replace file",
      hint: "Up to 4.5 MB. Text-based PDFs work best.",
      tooLarge: "File is too large. Keep PDFs under 4.5 MB.",
      wrongType: "Please choose a PDF file.",
      removeFile: "Remove file",
    },
    sample: {
      prompt:
        "Pick a sample to see how OfferShield works — no upload or paste required.",
      loaded: "Sample loaded. Ready to analyze.",
    },
    button: {
      analyze: "Analyze document",
      analyzing: "Analyzing…",
    },
    inline: "OfferShield provides educational information, not legal advice.",
  },
  analyzing: {
    messages: [
      "Reading your document…",
      "Identifying key clauses…",
      "Surfacing red flags…",
      "Mapping obligations…",
      "Drafting questions to ask…",
      "Scoring the risk…",
    ],
    etaPrefix: "ETA:",
    etaRange: (lo: number, hi: number) => `${lo}–${hi} min`,
    etaMinutes: (n: number) => `${n} min`,
    etaSeconds: (n: number) => `${n}s`,
    etaFinishing: "Finishing up…",
  },
  errorState: {
    title: "Something went wrong",
    retry: "Try again",
  },
  report: {
    heading: {
      tag: "Your report",
      title: "Read before you sign",
      generatedBy: "Generated by OfferShield",
    },
    download: {
      title: "Save this report",
      subtitle:
        "Download a copy for your records, to share with a lawyer, or to print.",
      htmlButton: "Save as HTML",
      markdownButton: "Save as Markdown",
      generating: "Preparing…",
    },
    risk: {
      tag: "Overall risk",
      outOf: (score: number) => ` / 100`,
    },
    exec: {
      tag: "Executive summary",
      fallback: "Contract",
    },
    plain: {
      tag: "Plain-English explanation",
      title: "Read before you sign",
    },
    clauses: {
      tag: "Key clauses",
      title: "What the main terms actually do",
    },
    redFlags: {
      tag: "Red flags",
      title: "Worth a second look",
      emptyTitle: "No major red flags detected",
      emptyBody:
        "Based on this analysis, the document does not contain terms that clearly warrant caution. You should still read the agreement and consider asking a lawyer about anything you don't fully understand.",
    },
    obligations: {
      tag: "Obligations",
      title: "Who owes what",
      you: "Your obligations",
      counterparty: "Counterparty's obligations",
      mutual: "Mutual obligations",
    },
    payment: {
      tag: "Payment & compensation",
      title: "The money side",
      amount: "Amount",
      schedule: "Schedule",
      lateFees: "Late fees",
      notes: "Notes",
    },
    termination: {
      tag: "Termination & renewal",
      title: "How the agreement ends",
      notice: "Notice required",
      renewal: "Renewal",
      cancellation: "Cancellation",
      notes: "Notes",
    },
    deadlines: {
      tag: "Deadlines & important dates",
      title: "Don't miss these",
    },
    missing: {
      tag: "Missing protections",
      title: "What this agreement doesn't cover",
    },
    ambiguous: {
      tag: "Ambiguous language",
      title: "Phrases worth clarifying",
      why: "Why it's unclear: ",
    },
    questions: {
      tag: "Questions to ask",
      title: "Before you sign",
      copy: "Copy all",
      copied: "Copied",
      copyAria: "Copy all questions",
    },
    negotiation: {
      tag: "Negotiation opportunities",
      title: "Concrete things to push back on",
    },
    confidence: {
      tag: "Confidence & caveat",
      title: "How much to trust this",
      educational: "Educational, not legal advice",
    },
    disclaimer: {
      title: "OfferShield provides educational information, not legal advice.",
      body:
        "The analysis above is generated by an AI and is meant to help you understand a document, not to replace a qualified lawyer. For any decision with real consequences, please consult a licensed attorney in your jurisdiction.",
    },
    documentType: (t: string) => `${t} · Confidence: `,
  },
};
// (No top-level `as const` — we want `meta.title` / `description` to
//  be typed as `string` so other locales can supply their own
//  translations. The `messages` array still uses `as const` below
//  to keep its tuple-of-literals shape — useful if a future change
//  wants to enumerate them.)
