import { z } from "zod";

/**
 * The structured shape OfferShield expects from the model.
 *
 * Designed to be:
 *   - exhaustive: covers every section the UI renders
 *   - defensive: every field has a default so a partial response
 *     still renders cleanly
 *   - portable: works the same on MiniMax, Anthropic, or any
 *     Anthropic-compatible proxy
 *
 * Note: we deliberately keep validation loose (no .min(1) on fields
 * that have a default) so a partial model response still renders.
 * Post-parse filters (in analyze.ts) drop empty entries from arrays.
 */

export const RiskLevel = z.enum(["low", "medium", "high"]);
export type RiskLevel = z.infer<typeof RiskLevel>;

export const Severity = RiskLevel;
export type Severity = RiskLevel;

export const Party = z.enum(["you", "counterparty", "mutual", "unclear"]);
export type Party = z.infer<typeof Party>;

export const Confidence = z.enum(["low", "medium", "high"]);
export type Confidence = z.infer<typeof Confidence>;

export const KeyClause = z.object({
  title: z.string().default("Clause"),
  explanation: z.string().default(""),
});

export const RedFlag = z.object({
  severity: Severity.default("medium"),
  title: z.string().default("Concern"),
  detail: z.string().default(""),
});

export const Obligations = z.object({
  party: Party.default("unclear"),
  items: z.array(z.string()).default([]),
});

export const PaymentTerms = z.object({
  amount: z.string().nullable().optional(),
  schedule: z.string().nullable().optional(),
  lateFees: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
});

export const Termination = z.object({
  notice: z.string().nullable().optional(),
  renewal: z.string().nullable().optional(),
  cancellation: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
});

export const Deadline = z.object({
  date: z.string().nullable().optional(),
  event: z.string().default("Event"),
});

export const AmbiguousPhrase = z.object({
  quote: z.string().default(""),
  whyUnclear: z.string().default(""),
});

export const AnalysisPayload = z.object({
  documentType: z.string().default("Contract"),
  riskScore: z
    .number()
    .min(0)
    .max(100)
    .default(50)
    .describe("Numeric 0–100 risk score. 0 = benign, 100 = highly concerning."),
  riskLevel: RiskLevel.default("medium"),
  riskExplanation: z
    .string()
    .default(
      "Score reflects the combination of red flags, missing protections, and one-sided terms present in the document.",
    ),
  executiveSummary: z
    .string()
    .default(
      "OfferShield could not produce a confident summary for this document. The text may be too short or unclear.",
    ),
  plainEnglishExplanation: z
    .string()
    .default(
      "The document appears to be a contract. Please paste a longer excerpt for a fuller plain-English explanation.",
    ),
  keyClauses: z.array(KeyClause).default([]),
  redFlags: z.array(RedFlag).default([]),
  obligations: z.array(Obligations).default([]),
  paymentTerms: PaymentTerms.default({}),
  termination: Termination.default({}),
  deadlines: z.array(Deadline).default([]),
  missingProtections: z.array(z.string()).default([]),
  ambiguousLanguage: z.array(AmbiguousPhrase).default([]),
  questionsToAsk: z
    .array(z.string())
    .default([
      "What happens if either party wants to end the agreement early?",
    ]),
  negotiationOpportunities: z.array(z.string()).default([]),
  confidence: Confidence.default("medium"),
  caveat: z
    .string()
    .default(
      "This is an educational explanation generated by an AI. It is not legal advice. Consult a qualified lawyer for any legal decision.",
    ),
});

export type AnalysisPayload = z.infer<typeof AnalysisPayload>;
